Block post base
CSIS-iLab/reconasia_wp pull request #40
Opened 2021-03-16 20:33 UTC by jdromero88

closes #39

2021-03-17 20:19 UTC, urchykli requested changes
Nice first pass on this, Jose!  I left some inline comments, but let's also do the following.

- Delete the file `wp-content/themes/reconasia/assets/_scss/blocks/issues/_reconasia-original.scss` since we don't need it.
- In `template-tags.php` on line 92 let's adjust the links so the word "and" is used before the last author when there are multiple authors.
- In `_post-meta.scss` let's remove `color: var(--post-meta);` on line 4, since we aren't using it.
- In `front-page.php`, we need two sections, one for recent posts and one for featured posts.  You don't need to handle the functionality, but we should add the other section, so you can style the post blocks based on the correct section.

2021-03-17 20:19 UTC, urchykli commented on wp-content/themes/reconasia/template-parts/block-post.php
> +			echo get_the_post_thumbnail();
Will you please make the thumbnail a link to the post and have the hover effect be applied to the title when you hover over the image?

2021-03-17 20:19 UTC, urchykli commented on wp-content/themes/reconasia/assets/_scss/components/_post-block.scss
> +  &__title {
Don't forget the hover effect.  The styles are at the top of the components page in a box called Post Title Link.

2021-03-17 20:19 UTC, urchykli commented on wp-content/themes/reconasia/assets/_scss/components/_post-meta.scss
> +  &__categories {
Let's ask Christina in the Recon Asia slack channel if this should have a hover state.

2021-03-17 20:19 UTC, urchykli commented on wp-content/themes/reconasia/template-parts/block-post.php
> +			reconasia_posted_on();
Let's use the [WP date format](https://wordpress.org/support/article/formatting-date-and-time/) to format the date correctly.  The function to call the posted on date accepts the format string, so you can do something like `reconasia_posted_on('M j, Y');`

2021-03-22 21:00 UTC, jnschrag commented
Closing this pull request because @jdromero88 is working on his changes on a new branch because of a broken rebase.

2021-03-22 21:00 UTC, closed without merging