Feat/post content styles
CSIS-iLab/reconasia_wp pull request #54
Opened 2021-04-05 18:44 UTC by smaraghi

These are the base post content styles. 

At the bottom of the Test Post Components & Blocks post, I added several components to test these styles including a table, list elements, external links, etc. 

Please let me know if there is anything I missed.

2021-04-05 20:43 UTC, urchykli requested changes
Thanks for helping out with this, Serven! In addition to some inline comments, I had the following notes. Please let me know if you have any questions.
- Let's remove the external link icon from the publication block title.
- We need inline link styles.  I added an inline link by the lists.
- We need to add font, etc for the external links.
- Focus styles for inline and external links.
- Is the external link icon supposed to be red on hover?
- We need to add a top border to the table.

2021-04-05 20:43 UTC, urchykli commented on wp-content/themes/reconasia/assets/_scss/pages/single.scss
> +    li::marker {
Can we add some space between the markers and the `li`s please?

2021-04-05 20:43 UTC, urchykli commented on wp-content/themes/reconasia/assets/_scss/pages/single.scss
> +        background-color: $color-bg-thead;
```suggestion
        background-color: $color-bg-light-300;
```

2021-04-05 20:43 UTC, urchykli commented on wp-content/themes/reconasia/assets/_scss/pages/single.scss
> +          background-color: $color-bg-tbody;
```suggestion
          background-color: $color-bg-light-200;
```

2021-04-05 20:43 UTC, urchykli commented on wp-content/themes/reconasia/assets/_scss/pages/single.scss
> +        border-left: 1px solid rgba(0, 0, 0, 0.15);
```suggestion
        border-left: 1px solid $color-black-115;
```

2021-04-05 20:43 UTC, urchykli commented on wp-content/themes/reconasia/assets/_scss/pages/single.scss
> +        border-bottom: 1px solid rgba(0, 0, 0, 0.15);
```suggestion
        border-bottom: 1px solid $color-black-115;
```

2021-04-05 20:43 UTC, urchykli commented on wp-content/themes/reconasia/assets/_scss/pages/single.scss
> +        border-bottom: 1px solid rgba(0, 0, 0, 0.3) !important;
```suggestion
        border-bottom: 1px solid $color-black-130 !important;
```

2021-04-05 20:43 UTC, urchykli commented on wp-content/themes/reconasia/assets/_scss/pages/single.scss
> +    figcaption {
We need to add the bottom underline to the caption.

2021-04-06 14:16 UTC, smaraghi commented on wp-content/themes/reconasia/assets/_scss/abstracts/_variables.scss
> +$color-bg-tbody: rgb(241, 243, 245);
The colors on figma were different rgbas which is why I added them. Let me know if you would like to forgo them

2021-04-06 15:24 UTC, urchykli commented on wp-content/themes/reconasia/assets/_scss/pages/single.scss
> +      &:focus {
We need to remove the underline on focus.

2021-04-06 15:37 UTC, smaraghi commented on wp-content/themes/reconasia/assets/_scss/blocks/post/_publications.scss
>        .csis-block__title,
With:

![image](https://user-images.githubusercontent.com/45780666/113737755-51838280-96cc-11eb-8f67-c3483a6f5b11.png)

Without:

![image](https://user-images.githubusercontent.com/45780666/113737837-63652580-96cc-11eb-8525-adee116a1401.png)

2021-04-06 15:38 UTC, smaraghi commented on wp-content/themes/reconasia/assets/_scss/blocks/post/_publications.scss
> +        color: $color-black-190;
With:

![image](https://user-images.githubusercontent.com/45780666/113738037-8ee81000-96cc-11eb-9a26-b91c030a9ccf.png)


Without:

![image](https://user-images.githubusercontent.com/45780666/113737974-8263b780-96cc-11eb-8a99-300277433bad.png)

2021-04-06 15:40 UTC, smaraghi commented on wp-content/themes/reconasia/assets/_scss/blocks/post/_publications.scss
> +        @include font-size(18px);
With:

![image](https://user-images.githubusercontent.com/45780666/113738455-e8e8d580-96cc-11eb-9e8d-9072a8de5a36.png)


Without:

![image](https://user-images.githubusercontent.com/45780666/113738421-e0909a80-96cc-11eb-8d22-dd7e9326667d.png)

2021-04-06 15:41 UTC, smaraghi commented on wp-content/themes/reconasia/assets/_scss/blocks/post/_publications.scss
> +        @include font-size(18px);
When its not on the a it is the wrong size - again another overwriting issue

2021-04-06 16:18 UTC, merged